server:
  port:

spring:
  profiles:
    default: dev

  datasource:
    url:
    username:
    password:
    driver-class-name:

  jpa:
    hibernate.ddl-auto:
    open-in-view:
    show-sql:
    properties:
      hibernate.format_sql:
      hibernate.default_batch_fetch_size:

  servlet:
    multipart:
      max-file-size:
      max-request-size:

  # OAuth Config
  security:
    oauth2.client:
      registration:
        google:
          clientId:
          clientSecret:
          scope:
        kakao:
          clientId:
          clientAuthenticationMethod:
          authorizationGrantType:
          redirectUri:
          scope:
          clientName:
      # Kakao Provider 설정
      provider:
        kakao:
          authorizationUri:
          tokenUri:
          userInfoUri:
          userNameAttribute:

# S3
cloud:
  aws:
    credentials:
      access-key:
      secret-key:
    s3:
      bucket:
    region:
      static:
    stack:
      auto:

# Image File Rule & Info
image:
  allow-extensions:
  limit-size:
  user-profile-image:
    default-image-name:
    default-image-path:
  project-thumbnail-image:
    default-image-name:
    default-image-path:
  article-thumbnail-image:
    default-image-full-path: